DELETE FROM USERS;
DELETE FROM STATUS;
DELETE FROM ROLE;

INSERT INTO ROLE(ID,NAME,DESCRIPTION) VALUES(1,'ADMINISTRADOR','');

INSERT INTO STATUS(ID,NAME,DESCRIPTION) VALUES(1,'ACTIVO','');
INSERT INTO STATUS(ID,NAME,DESCRIPTION)  VALUES(2,'INACTIVO','');
INSERT INTO STATUS(ID,NAME,DESCRIPTION)  VALUES(3,'ELIMINADO','');

INSERT INTO USERS(ID,USER_NAME,PASSWORD,EMAIL,ROLE_ID,STATUS_ID) VALUES(1,'admin','admin','admin@yopmail.com',1,1);
