DROP TABLE IF EXISTS USERS
;
CREATE TABLE USERS
(
	ID BIGINT NOT NULL,
	USER_NAME BIGINT NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50),
	STATUS_ID BIGINT NOT NULL,
	ROLE_ID BIGINT NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE UQ_USERS_ID(ID),
	UNIQUE UQ_USERS_USER_NAME(USER_NAME),
	KEY (ROLE_ID),
	KEY (STATUS_ID)
) 
;


ALTER TABLE USERS ADD CONSTRAINT FK_USERS_ROLE 
	FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
;

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_STATUS 
	FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID)
;

