package com.amc.ebg.domain.entities;
// Generated 28-jul-2013 14:00:33 by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="ebg"
)
public class Users  implements java.io.Serializable {


     private Long id;
     private Role role;
     private Status status;
     private String userName;
     private String password;
     private String email;

    public Users() {
    }

	
    public Users(Long id, Role role, Status status, String userName, String password) {
        this.id = id;
        this.role = role;
        this.status = status;
        this.userName = userName;
        this.password = password;
    }
    public Users(Long id, Role role, Status status, String userName, String password, String email) {
       this.id = id;
       this.role = role;
       this.status = status;
       this.userName = userName;
       this.password = password;
       this.email = email;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLE_ID", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_ID", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    
    @Column(name="USER_NAME", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


